// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xumxqzuizmrpecpcythv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bXhxenVpem1ycGVjcGN5dGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NzkwMTksImV4cCI6MjA2NjA1NTAxOX0.1o8DFJo4YjTR_GLTWs1XHpTcnD0hcH_Bfc2qJ24MUOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);